### ISSUE TITLE
Crashing for below layout configuration

### ISSUE THREAD

**Issue by mukyasa** [kishikawakatsumi/IBPCollectionViewCompositionalLayout#118]
let itemSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1.0),
                                              heightDimension: .estimated(100))
        let item = NSCollectionLayoutItem(layoutSize: itemSize)
        item.edgeSpacing = NSCollectionLayoutEdgeSpacing(leading: .fixed(8),
                                                         top: .fixed(8),
                                                         trailing: .fixed(8),
                                                         bottom: .fixed(8))
        let groupSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1.0),
                                               heightDimension: .estimated(100))
        let group = NSCollectionLayoutGroup.horizontal(layoutSize: groupSize,
                                                       subitems: [item])

        let section = NSCollectionLayoutSection(group: group)
        let layout = UICollectionViewCompositionalLayout(section: section)
        return layout

Hello Team,
Thank you for this library, I have been playing with estimate dimension and when i try to set the below code
```
       item.edgeSpacing = NSCollectionLayoutEdgeSpacing(leading: .fixed(8),
                                                         top: .fixed(8),
                                                         trailing: .fixed(8),
                                                         bottom: .fixed(8)) 
```
it **crashes** at this line

![Screenshot 2019-09-26 at 12 16 43 PM](https://user-images.githubusercontent.com/7480780/65664731-98180b80-e057-11e9-8de1-d7dc07be9a22.png)

**Comment by kishikawakatsumi** [comment]
@mukyasa The code also goes into UIKit's `UICollectionViewCompositionalLayout` in an infinite loop. 
The layout does not work correctly even on UIKit's `UICollectionViewCompositionalLayout` unfortunately.

It's a UIKit's bug.
So please report the issue to Apple. I also send bug report to Apple.

Thank you for reporting! Feel free to reopen if you have any questions or further info.
