### ISSUE TITLE
Orthogonal views not respecting trailing contentInset

### ISSUE THREAD

**Issue by notjosh** [kishikawakatsumi/IBPCollectionViewCompositionalLayout#78]
There is a regression from 3-4 days ago.

As far as I can tell, `top` and `leading` are handled [here](https://github.com/kishikawakatsumi/IBPCollectionViewCompositionalLayout/blob/0ebcd11a3cc9973e7f71a005704be7821de77817/Sources/IBPCollectionViewCompositionalLayout/IBPCollectionCompositionalLayoutSolver.m#L59-L60) but there's no corresponding `trailing`/`bottom` on the other side.

I tried quickly to track it down, but nothing was obvious to me.

**Comment by notjosh** [comment]
Repro up on branch: https://github.com/notjosh/IBPCollectionViewCompositionalLayout/tree/sample-orthogonal-trailing-contentinset (ref: [`OrthogonalScrollingWithInsetsViewController`](https://github.com/notjosh/IBPCollectionViewCompositionalLayout/blob/sample-orthogonal-trailing-contentinset/Example/Example/Samples%20from%20compositional-layouts-kit/Compositional%20Layouts%20VCs/OrthogonalScrollingWithInsetsViewController.swift))

In the screenshots, the top section is scrolled all the way to the right.

There are three issues I see here, two are related to `contentInset`:

- iOS 12.4 with section `contentInset` does not include `trailing` space at the end of the row
- iOS 12.4 with section `contentInset` makes each of the cells less wide (this seems related to `.fractionalWidth`, it's the correct size with `.absolute()`) - we can track this as a separate issue, if it's not related)
- iOS 12.4 doesn't seem to use the `bottom` of `contentInset` on `item`s (this seems related, but we can track it as a separate issue)

OS | Without section `contentInset` | With section `contentInset`
--- | --- | ---
iOS 12.4 | <img width="514" alt="image" src="https://user-images.githubusercontent.com/33126/63562598-12161b80-c513-11e9-9dee-52db348aa353.png"> | <img width="514" alt="image" src="https://user-images.githubusercontent.com/33126/63562570-fc085b00-c512-11e9-99ec-16162e7a870e.png">
iOS 13 | <img width="514" alt="image" src="https://user-images.githubusercontent.com/33126/63562632-2a863600-c513-11e9-92e8-0b3eb81f9322.png"> | <img width="514" alt="image" src="https://user-images.githubusercontent.com/33126/63562540-e4c96d80-c512-11e9-8bfd-9d1aafb7d9c5.png">

**Comment by kishikawakatsumi** [comment]
Fixed by https://github.com/kishikawakatsumi/IBPCollectionViewCompositionalLayout/pull/85

Thank you for reporting!
