### ISSUE TITLE
About iOS minimum deployment target version

### ISSUE THREAD

**Issue by qhhonx** [kishikawakatsumi/IBPCollectionViewCompositionalLayout#98]
I built IBPCollectionViewCompositionalLayout target with `8.0` deployment target and no errors happened. So can we decrease the minimum deployment target to `8.0` so that more products can adopt this awesome library? Or  maybe I missing some considerations for the current `10.0` deployment target version?

**Comment by kishikawakatsumi** [comment]
@qhhonx The reason is just not tested enough. I'm not sure if it works well on iOS 8. 
Do you use this library on iOS 8? I can decrease the deployment target if you report issues.

**Comment by qhhonx** [comment]
@kishikawakatsumi Ok, I see that. I have not used it in production now. Our product is set to iOS 9 as minimum deployment target version. If we decide to integrate it, we would like take a PR and report test issues.
